spring:
  application:
    name: spring-boot-invest-sync

google:
  sheets:
    credentials: ${GOOGLE_SHEETS_CREDENTIALS}

integrations:
  apis:
    br-api:
      url: ${BR_API_URL}
      token: ${BR_API_TOKEN}
    usa-api:
      url: ${USA_API_URL}
      token: ${USA_API_TOKEN}
